# Generated by Django 5.0.1 on 2024-01-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_trainee_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
